Gemstar.BSPMS.HotelScanOder.Web/Controllers/InSingle_BController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Gemstar.BSPMS.HotelScanOrder.Common;
using Gemstar.BSPMS.HotelScanOrder.Common.Common;
using Gemstar.BSPMS.HotelScanOrder.Common.Pos.Action;
using Gemstar.BSPMS.HotelScanOrder.Common.Pos.Bill;
using Gemstar.BSPMS.HotelScanOrder.Common.Pos.Item;
using Gemstar.BSPMS.HotelScanOrder.Common.Pos.PayBill;
using Gemstar.BSPMS.HotelScanOrder.Common.Pos.PayMethod;
using Gemstar.BSPMS.HotelScanOrder.Common.Pos.Request;
using Gemstar.BSPMS.HotelScanOrder.Common.Pos.Tab;
using Gemstar.BSPMS.HotelScanOrder.Common.PosEnum;
using Gemstar.BSPMS.HotelScanOrder.Web.Models;
using Gemstar.BSPMS.HotelScanOrder.Web.Models.Pay;

namespace Gemstar.BSPMS.HotelScanOrder.Web.Controllers
{
    /// <summary>
    /// 扫码点餐用户使用的控制器
    /// </summary>
    public class InSingle_BController : Base_BController
    {
        public ActionResult Index(OpenTabView model)
        {

            //当前餐台Id 不等于缓存的餐台ID，调用接口获取数据
            var currentinfo = GetService<ICurrentInfo>();
            currentinfo.RefeId = model.RefeId; //当前操作的营业点ID存储到session中
            currentinfo.SaveValues();

            var postItemList = commonHelper.SetItemListB(model.RefeId, model.Tabid);

            //消费项目大类
            var itemSubClass = postItemList.MyDistinct(w => w.Itemsubid).ToList();

            //取第一个分类下的菜式
            var itemList = new List<ItemResultModel>();
            foreach (var item in postItemList)
            {
                var s = postItemList.Where(w => w.Itemsubid == item.Itemsubid && w.IsDefault == true).ToList();
                itemList.AddRange(s);
                break;
            }

            ViewBag.itemSubClass = itemSubClass;    //分类
            ViewBag.itemList = itemList;            //消费项目
            ViewBag.OpenTabView = model;
            ViewBag.OpenId = CurrentInfo.OpenId;    //openId
            ViewBag.WxPaytype = currentinfo.WxPaytype;      //扫码点菜支付方式
            ViewBag.TabNo = currentinfo.TabNo;      //餐台编码
            ViewBag.TabName = currentinfo.TabName;      //餐台明细

            return View();
        }
        /// <summary>
        /// 分部视图，根据分类ID 获取消费项目
        /// </summary>
        /// <param name="subClassId">分类ID</param>
        /// <param name="tabId">餐台ID</param>
        /// <param name="refeId">营业点ID</param>
        /// <returns></returns>
        public PartialViewResult _ItemList(string subClassId, string tabId, string refeId)
        {
            var postItemList = commonHelper.SetItemListB(refeId, tabId);
            ViewBag.specFlag = "1";
            //筛选分类下的消费项目
            var itemList = new List<ItemResultModel>();
            foreach (var item in postItemList)
            {
                var s = postItemList.Where(w => w.Itemsubid == subClassId && w.IsDefault == true).ToList();
                itemList.AddRange(s);
                break;
            }

            return PartialView("_ItemList", itemList);
        }

        #region 规格业务代码

        /// <summary>
        /// 有规格的消费项目查询出单位以及作法列表
        /// </summary>
        /// <param name="itemId">消费项目ID</param>
        /// <returns></returns>
        public JsonResult SpecList(string itemId, string tabId, string refeId)
        {
            var postItemList = commonHelper.SetItemListB(refeId, tabId);
            //单位列表
            var unitList = postItemList.Where(w => w.ItemId == itemId).ToList();

            //要求列表
            var requestList = commonHelper.GetRequestList(refeId);

            //作法列表
            var actionList = commonHelper.GetActionListByItemId(itemId);

            //返回结果
            var result = new
            {
                Unit = unitList,
                Request = requestList,
                Action = actionList
            };
            //查询消费项目
            return Json(JsonResultData.Successed(result));
        }


        #endregion


        /// <summary>
        /// 已点菜式
        /// </summary>
        /// <returns></returns>
        public PartialViewResult _OrderList(string tabId, string refeId, string detailStr)
        {
            var currentinfo = GetService<ICurrentInfo>();
            List<OrderListModel> result = new List<OrderListModel>();
            //要求列表
            var request = commonHelper.GetRequestList(refeId);

            //账单明细
            List<billDetailViewModel> detailList = new List<billDetailViewModel>();

            //还未落单的数据
            if (!string.IsNullOrEmpty(detailStr))
            {
                detailList = JsonHelp.Deserialize<List<billDetailViewModel>>(detailStr);
            }

            List<BillDetailResultModel> detail = new List<BillDetailResultModel>();
            //调用接口查询已经落单的账单明细
            if (Convert.ToByte(currentinfo.WxPaytype) == (byte)WxPaytype.餐后付款) //如果是餐后付款 需要查询出之前的账单以及账单明细信息
            {
                detail = commonHelper.GetBillQuery(refeId, tabId);
            }
            foreach (var item in detail)
            {
                var billDetail = new billDetailViewModel();
                commonHelper.SetModel(billDetail, item);
                //已经存在的数据查询出来
                detailList.Add(billDetail);

            }
            decimal? totAmount = 0;
            //查询做法
            foreach (var item in detailList)
            {
                if (item.Tagcharge != (int)PosbillDetailStatus.保存)
                {
                    totAmount = item.TotAmount;

                }
                OrderListModel model = new OrderListModel();
                model.RequestList = request;    //要求

                //单位列表
                var postItemList = commonHelper.SetItemListB(refeId, tabId);
                model.UnitList = postItemList.Where(w => w.ItemId == item.ItemId).ToList();

                //做法
                if (item.IsAutoaction != "False")
                    model.ActionList = commonHelper.GetActionListByItemId(item.ItemId);
                else
                    model.ActionList = null;

                var actionListB = new List<BillDetailActionModel>();
                //作法分组
                var actionGroupList = new List<BillDetailActionGroup>();
                if (item.Tagcharge == (int)PosbillDetailStatus.保存)
                {
                    var actionList = JsonHelp.Deserialize<List<BillDetailActionModel>>(item.ActioName ?? "");
                    if (actionList != null && actionList.Count > 0)
                    {
                        //  actionList.OrderBy(w => w.groupid);
                        actionList.Sort((a, b) => a.groupid.CompareTo(b.groupid));
                        //通过分组ID进行分组查询出需要的数据
                        foreach (IGrouping<string, BillDetailActionModel> group in actionList.GroupBy(x => x.groupid))
                        {
                            var s = new BillDetailActionGroup();
                            string resultSplit = "";
                            s.groupid = group.Key;
                            foreach (var actionModel in group)
                            {
                                s.ActionIds += resultSplit + actionModel.actionid;
                                s.ActionNames += resultSplit + actionModel.actionname;
                                resultSplit = ",";
                            }
                            actionGroupList.Add(s);
                        }

                    }

                }
                else
                {
                    //调用接口查询做法
                    var actionList = commonHelper.GetBillDetailAction(refeId, tabId).Where(w => w.RowId == item.RowId);
                    //数据库的做法根据前端规格赋值
                    foreach (var action in actionList)
                    {
                        BillDetailActionModel actionModel = new BillDetailActionModel()
                        {
                            rowid = action.RowId.ToString(),
                            groupid = action.GroupId.ToString(),
                            actionid = action.ActionId,
                            actionname = action.ActionName,
                            addprice = action.AddPrice.ToString(),
                            multiple = "",
                            deptclassno = "",
                            pdano = "",
                            status = "0"

                        };
                        actionListB.Add(actionModel);
                    }
                    if (actionList != null && actionListB.Count > 0)
                    {
                        actionList = actionList.OrderBy(w => w.GroupId).ToList();
                        foreach (IGrouping<int?, GetBillDetailActionResultModel> group in actionList.GroupBy(x => x.GroupId))
                        {
                            var s = new BillDetailActionGroup();
                            string resultSplit = "";
                            s.groupid = group.Key.ToString();
                            foreach (var actionModel in group)
                            {
                                s.ActionIds += resultSplit + actionModel.ActionId;
                                s.ActionNames += resultSplit + actionModel.ActionName;
                                resultSplit = ",";
                            }
                            actionGroupList.Add(s);
                        }
                    }
                }
                model.ActionGroupList = actionGroupList;

                //账单明细
                model.BillDetail = item;
                model.ActionListStr = JsonHelp.Serialize(actionListB);
                result.Add(model);

            }

            //是否显示买单

            ViewBag.WxPaytype = currentinfo.WxPaytype;  //点菜支付，餐后支付
            ViewBag.TotAmount = totAmount;

            return PartialView("_OrderList", result);
        }


        /// <summary>
        /// 处理账单明细数据
        /// </summary>
        /// <param name="tabId">餐台ID</param>

Gemstar.BSPMS.HotelScanOder.Web/Views/InSingle_B/PaymentSuccess.cshtml
@{
    /**/

    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Css{
    <style>
        .paymentSuccess {
            height: 100%;
            padding: 15px;
            text-align: center;
        }

        .paymentSuccess i {
            font-size: 0.5rem;
            color: #00bb00;
        }

        .paymentSuccess span {
            font-size: 0.2rem;
            line-height: 0.2rem;
        }

        .paymentSuccess div {
            font-size: 0.2rem;
            line-height: 0.5rem;
        }
        .mui-bar-nav {
            height: 0.48rem;
            background-color: #FF6F28;
        }

        .mui-bar-nav .mui-icon-left-nav {
            margin: 0;
            padding: 0;
            height: 0.48rem;
            width: 1rem;
            line-height: 0.88rem;
        }

        .mui-bar-nav .mui-title {
            height: 0.48rem;
            line-height: 0.48rem;
            font-size: .34rem;
            color: #FFFFFF;
        }

    </style>
}

@{

    @*<div class="paymentSuccess">
            <i class="fa fa-check-circle" aria-hidden="true"></i><br />
            <span>支付成功</span><br />
            <div id="countDown">5秒 查看订单</div>
            <button type="button" class="mui-btn mui-btn-success mui-btn-block" onclick="returnHome()">查看订单</button>
        </div>*@
    <input id="refeId" type="hidden" value="@ViewBag.RefeId" />
    <input id="tabid" type="hidden" value="@ViewBag.Tabid" />
    <div class="paymentSuccess">
        <i class="fa fa-check-circle" aria-hidden="true"></i><br />
        <span>支付成功</span><br />
        <div id="countDown">5秒 返回首页</div>
        <button type="button" class="mui-btn mui-btn-success mui-btn-block" onclick="returnHome()">返回首页</button>
    </div>

}


@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {

        });

       var time = setInterval(showTime, 1000);
        var second = 5;
        function showTime() {
            if (second == 0) {
                clearInterval(time);
                location.href = '@Url.Action("Index", "InSingle_B")?RefeId=' + $("#refeId").val() + '&Tabid=' + $("#tabid").val();
                //Tabid=000388035&RefeId=000388001
            }
            else {
                $("#countDown").text(second + '秒 返回首页');
                second--;
            }
        }

        function returnHome()
        {
            location.href = '@Url.Action("Index", "InSingle_B")?RefeId=' + $("#refeId").val() + ' & Tabid=' + $("#tabid").val();

        }
        WeixinJSBridge.call('hideToolbar');
    </script>
}  

Gemstar.BSPMS.HotelScanOder.Web/Views/InSingle_B/_ItemList.cshtml
@{
    Layout = null;
}
@model List<Gemstar.BSPMS.HotelScanOrder.Common.Pos.Item.ItemResultModel>

@{
    foreach (var item in Model.Where(s=>s.ItemIsCurrent==false && s.ItemIsHandWrite==false))
    {
        <li class="mui-table-view-cell mui-media">
            <img class="mui-media-object mui-pull-left" src="@item.PicUrl2" />
            <div class="mui-media-body">
                <h4>@item.ItemName</h4>
                <p class='mui-ellipsis'>
                    <i class="fa fa-rmb price" aria-hidden="true"></i><label class="price">@item.Price</label>
                </p>
                @if (item.IsAutoaction == true || item.IsMultiUnit == true)
                {
                    if (item.IsSellout == true)    //沽清菜式无法进行点击
                    {
                        <div class="specification">
                            <div type="button"  style="background-color:#acacac;border-width:1px;" >规格</div>
                        </div>
                    }
                    else
                    {
                        <div class="specification">
                            <div type="button" style="border-width:1px;" onclick="selectSpec(this,@ViewBag.specFlag)" data-name="@item.ItemName" data-id="@item.ItemId" data-subclassId="@item.Itemsubid" data-isSellout="@item.IsSellout" data-isLargess="@item.IsLargess" data-isMultiUnit="@item.IsMultiUnit" data-isAutoaction="@item.IsAutoaction" data-itemName="@item.ItemName" data-unitName="@item.UnitName">规格</div>
                        </div>
                    }


                }
                else
                {
                    if (item.IsSellout == true)
                    {
                        <div class="addBtn">

                            <a class="addC"></a>

                        </div>
                    }
                    else
                    {
                        <div class="addBtn">
                            <a onclick="reductionQuantity(this)" class="addB" style="display: none;" data-id="@item.ItemId" data-unitId="@item.UnitId" data-price="@item.Price" data-subclassId="@item.Itemsubid" data-isSellout="@item.IsSellout" data-isLargess="@item.IsLargess" data-isMultiUnit="@item.IsMultiUnit" data-isAutoaction="@item.IsAutoaction" data-itemName="@item.ItemName" data-unitName="@item.UnitName"></a>

                            <span class="inputSpan" data-id="@item.ItemId"></span>
                            <a onclick="addQuantity(this)" class="addA" data-id="@item.ItemId" data-unitId="@item.UnitId" data-price="@item.Price" data-subclassId="@item.Itemsubid" data-isSellout="@item.IsSellout" data-isLargess="@item.IsLargess" data-isMultiUnit="@item.IsMultiUnit" data-isAutoaction="@item.IsAutoaction" data-itemName="@item.ItemName" data-unitName="@item.UnitName"></a>

                        </div>

                    }


                }




            </div>
        </li>
            }

    }

Gemstar.BSPMS.HotelScanOder.Web/Views/InSingle_B/_OrderList.cshtml
<link rel="stylesheet" href="../../Content/ScanOrder/pos.css">
@{
    Layout = null;

}
@model List<Gemstar.BSPMS.HotelScanOrder.Web.Models.OrderListModel>

@using Gemstar.BSPMS.HotelScanOrder.Common.PosEnum
<div class="pos-tableHeader">
    <div class="pos-serial"></div>
    <div class="pos-name">菜名</div>
    <div class="pos-unit">单位</div>
    <div class="pos-num">数量</div>
    <div class="pos-price">单价</div>
</div>
<ul class="pos-tableList">
    @{
        var index = 1;
        foreach (var item in Model)
        {
            <li data-id="@item.BillDetail.ItemId" data-status="@item.BillDetail.Tagcharge" data-isModify="0" data-rowId="@item.BillDetail.RowId" data-itemName="@item.BillDetail.ItemName">

                <div class="pos-item" data-tagcharge="@item.BillDetail.Tagcharge">
                    <div class="pos-serial">@index</div>
                    <div class="pos-name">@item.BillDetail.ItemName</div>
                    <div class="pos-unit">@item.BillDetail.UnitName</div>
                    <div class="pos-num">@string.Format("{0:F}", item.BillDetail.Quan)</div>
                    <div class="pos-price ">@string.Format("{0:F}", item.BillDetail.Price)</div>
                </div>
                <div class="pos-details">
                    <div class="flex number">
                        <div class="title1">数量</div>
                        <div class="number-operation">
                            <div class="minus" onclick="_orderMinus($(this))" data-itemId="@item.BillDetail.ItemId" data-tagcharge="@item.BillDetail.Tagcharge"></div>
                            <span>@string.Format("{0:F}", item.BillDetail.Quan)</span>
                            <div class="add" onclick="_orderAdd($(this))" data-itemId="@item.BillDetail.ItemId" data-tagcharge="@item.BillDetail.Tagcharge"></div>
                        </div>

                    </div>
                    <div class="unit-flex">
                        <div class="title1">单位</div>
                        <div class="list" style="margin-left:.02rem">
                            @{
                                if (item.UnitList.Count == 1)
                                {
                                    <a class="mui-btn spec-active" data-price="@item.UnitList[0].Price" data-name="@item.UnitList[0].UnitName" data-id="@item.UnitList[0].UnitId" data-itemId="@item.BillDetail.ItemId" data-tagcharge="@item.BillDetail.Tagcharge">@item.UnitList[0].UnitName</a>
                                }
                                else
                                {
                                    foreach (var unit in item.UnitList)
                                    {
                                        if (item.BillDetail.UnitId == unit.UnitId)
                                        {
                                            <a class="mui-btn spec-active" onclick="_orderSelectUnit($(this))" data-price="@unit.Price" data-name="@unit.UnitName" data-id="@unit.UnitId" data-itemId="@item.BillDetail.ItemId" data-tagcharge="@item.BillDetail.Tagcharge">@unit.UnitName</a>
                                        }
                                        else
                                        {
                                            <a class="mui-btn " onclick="_orderSelectUnit($(this))" data-price="@unit.Price" data-name="@unit.UnitName" data-id="@unit.UnitId" data-itemId="@item.BillDetail.ItemId" data-tagcharge="@item.BillDetail.Tagcharge">@unit.UnitName</a>
                                        }
                                    }
                                }

                            }

                        </div>
                    </div>
                    @{
                        if (item.BillDetail.IsAutoaction == "False")
                        {
                            if (!string.IsNullOrEmpty(item.BillDetail.ActioName))
                            {
                                <div class="unit-flex">
                                    <div class="title1">做法</div>
                                    <div class="list" style="margin-left:.02rem">
                                        @foreach (var actionGroup in item.BillDetail.ActioName.Split('/'))
                                        {
                                            foreach (var action in actionGroup.Split(','))
                                            {
                                                <a class="mui-btn" onclick="_orderCancelAction($(this))" data-itemId="@item.BillDetail.ItemId" data-tagcharge="@item.BillDetail.Tagcharge">@action</a>
                                            }
                                        }
                                    </div>
                                </div>
                            }
                        }
                        else
                        {
                            if (item.ActionList != null && item.ActionList.Count > 0)
                            {
                                <div class="unit-flex">
                                    <div class="title1">做法</div>
                                    <div class="list" style="margin-left:.02rem">
                                        @foreach (var action in item.ActionList)
                                        {
                                            <a class="mui-btn " onclick="_orderSelectAction($(this))" data-itemId="@item.BillDetail.ItemId" data-tagcharge="@item.BillDetail.Tagcharge" data-id="@action.ActionId" data-name="@action.ActionName">@action.ActionName</a>
                                        }
                                    </div>
                                </div>
                            }
                        }

                    }
                    @{
                        if (item.ActionList != null && item.ActionList.Count > 0)
                        {
                            <div class="unit-flex">
                                <div class="title1">已点作法</div>
                                <div class="list" style="margin-left:.02rem">
                                    @{
                                        foreach (var action in item.ActionGroupList)
                                        {

                                            <a class="mui-btn " data-id="@action.groupid" data-ids="@action.ActionIds" data-names="@action.ActionNames" onclick="_orderSelectActionGroup($(this))">@action.ActionNames</a>


                                        }
                                    }
                                    <a id="@("addactionGrp_"+item.BillDetail.ItemId.Trim()+"_"+item.BillDetail.RowId)" class="mui-btn spec-active" onclick="_orderSelectActionGroup($(this))" data-id="" data-ids="" data-names="">+</a>
                                    @{
                                        if (item.BillDetail.Tagcharge != (int)PosbillDetailStatus.保存)
                                        {
                                            <input type="hidden" value="@item.ActionListStr" id="@("input_"+item.BillDetail.ItemId.Trim()+"_"+item.BillDetail.RowId)" />
                                        }
                                    }

                                </div>
                            </div>}


                    }

                    @*<div class="unit-flex">
                        <div class="title1">要求</div>
                        <div class="list" style="margin-left:.02rem">
                            @{
                                var requestArr = item.BillDetail.Request ?? "";
                                foreach (var request in item.RequestList)
                                {
                                    if (requestArr.Contains(request.Name))
                                    {
                                        <a class="mui-btn spec-active" onclick="_orderRequest($(this))" data-itemId="@item.BillDetail.ItemId" data-id="@request.RequestId" data-names="@request.Name" data-tagcharge="@item.BillDetail.Tagcharge">@request.Name</a>
                                    }
                                    else
                                    {
                                        <a class="mui-btn " onclick="_orderRequest($(this))" data-itemId="@item.BillDetail.ItemId" data-id="@request.RequestId" data-names="@request.Name" data-tagcharge="@item.BillDetail.Tagcharge">@request.Name</a>
                                    }
                                }
                            }
                        </div>
                    </div>*@
                    <div class="buy">
                        @*<div class="send-btn" onclick="ZengSong($(this))">赠送</div>*@
                        <div class="cancel-btn" onclick="CancelItem($(this))">取消</div>
                        @*<div class="high-btn">高级</div>
                            <div class="buy-btn">落单</div>*@
                    </div>
                </div>
            </li>

            index++;
        }
    }

</ul>

<div class="footer-box">
    <div class="pos-footer">
        <div class="footer-left">
            <em class="footer-num">数量：3</em>
            <div class="footer-price">
                <span>合计：</span>
                <p>￥</p>
            </div>
        </div>
        <div class="footer-right">
            @{
                if (ViewBag.WxPaytype == "1") //点菜支付
                {
                    <a class="footer-pay" onclick="PayMethod()">买单</a>
                }
                else
                {
                    <a class="footer-buy" onclick="beAlone()">落单</a>
                    @*<a class="footer-pay" onclick="PayMethod()">买单</a>*@
                }
            }

        </div>
        <input type="hidden" value="@ViewBag.TotAmount" id="totalAmount" />
    </div>
</div>

Gemstar.BSPMS.HotelScanOder.Web/Views/InSingle_B/_QueryItemList.cshtml
<style>
    .form {
        margin: 5px;
        border: 1px #acacac solid;
        width: 70%;
        border-radius: 8px;
        float: left;
        display: block;
    }

    input[type=search] {
        margin: 0px;
        padding: 0px;
    }

    .acancel {
        float: left;
        margin-left: 5px;
        font-size: 17px;
        line-height: 50px;
    }
    #itemResultList .mui-table-view .mui-media-object {
    height: 1.8rem;
    width: 1.8rem;
    line-height: 1.8rem;
    max-width:1.8rem ;
}
</style>
<header class="mui-bar mui-bar-nav">
    <a class=" mui-icon mui-icon-left-nav mui-pull-left ordersys-back" onclick="closeQuery()"></a>
    <form action="" id="fromquery" style="width:70%;float:left;margin: 8px;">
        <div class="mui-indexed-list-search mui-input-row ">
            <input id="searchIpt" type="search" class="mui-input-clear mui-indexed-list-search-input" style="background-color:#f7f7f7;height:.6rem;margin:.14rem 0" placeholder="搜索">
        </div>
    </form>
    <a class="acancel" style="color:#ffffff;" onclick="searchItemData(event,true)">搜索</a>
</header>
<!--暂留用于存储最近搜索记录-->
<div>
</div>
<!--搜素结果-->
<div id="itemResultList" style="margin-top:0.9rem;">
    <ul id="ul_searchItemList" class="mui-table-view">
    </ul>
</div>